const types = {
  AUTH_FETCH: "AUTH/fetch",
  AUTH_SUCCESS: "AUTH/success",
  AUTH_ERROR: "AUTH/error",

  PORTFOLIO_FETCH: "PORTFOLIO/fetch",
  PORTFOLIO_DATA: "PORTFOLIO/data",
  PORTFOLIO_ERROR: "PORTFOLIO/error",
  PORTFOLIO_RESET: "PORTFOLIO/reset",

  PORTFOLIO_VALUATION_FETCH: "PORTFOLIO_VALUATION/fetch",
  PORTFOLIO_VALUATION_DATA: "PORTFOLIO_VALUATION/data",
  PORTFOLIO_VALUATION_ERROR: "PORTFOLIO_VALUATION/error",
  PORTFOLIO_VALUATION_RESET: "PORTFOLIO_VALUATION/reset",
};
export default types;
